/**
 * Build chat-menu from the SINGLE TypeScript source (src/core + src/host)
 * into both installable forms:
 *
 *   lib/                    bundle form (dsh plugin add)
 *     index.js              host half — ESM plugin (webServer route)
 *     client.js             browser half — module-loader factory (official id)
 *     client-registry.js    browser half — module-loader factory (registry id)
 *   dynamic/                dynamic form (cordis_define function bodies)
 *     host.js               host half — harness.handle bridge
 *     client.js             browser half — closure-symbol body
 *
 * The client core (src/core/menu-core.ts) bundles to an IIFE that both
 * client artifacts inline; each shell only supplies the environment glue
 * (React source, listing transport, module export form). The host core
 * (src/core/host-core.ts) is shared by both host wrappers via esbuild.
 */
import { build } from 'esbuild'
import { mkdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = ['node20', 'es2020']

await mkdir(join(root, 'lib'), { recursive: true })
await mkdir(join(root, 'dynamic'), { recursive: true })

// 1) Bundle host: ESM function plugin (single file, core inlined).
await build({
  entryPoints: [join(root, 'src/host/bundle.ts')],
  outfile: join(root, 'lib/index.js'),
  bundle: true,
  format: 'esm',
  platform: 'node',
  target,
})

// 2) Dynamic host: IIFE global + `return` → a valid function body.
const dynHost = await build({
  entryPoints: [join(root, 'src/host/dynamic.ts')],
  bundle: true,
  format: 'iife',
  globalName: 'CHATMENU_HOST',
  platform: 'node',
  target,
  write: false,
})
await writeFile(
  join(root, 'dynamic/host.js'),
  '// generated by scripts/build.mjs — single source: src/core/host-core.ts + src/host/dynamic.ts\n'
  + dynHost.outputFiles[0].text
  + '\nreturn CHATMENU_HOST;\n',
)

// 3) Client core: browser IIFE inlined into both client artifacts.
// JSX 用 classic 运行时（React.createElement）——React 由两种形态的环境注入，自动运行时不可用。
const core = await build({
  entryPoints: [join(root, 'src/core/menu-core.tsx')],
  bundle: true,
  format: 'iife',
  globalName: 'CHATMENU_CORE',
  platform: 'browser',
  target,
  jsx: 'transform',
  write: false,
})
const coreText = core.outputFiles[0].text

const bundleClientTemplate = (id) => `// generated by scripts/build.mjs — single source: src/core/menu-core.ts
window.__ModuleLoader__.load({
  id: ${JSON.stringify(id)},
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports
    const React = require('react')
${coreText}
    async function fsmenuList(sessionId, path, filter) {
      const params = new URLSearchParams({ sessionId, path, filter })
      const res = await fetch('/chat-menu/list?' + params.toString())
      return res.json()
    }
    const apply = CHATMENU_CORE.buildApply({ React, list: fsmenuList })
    module.exports = { name: 'dsh-plugin-chat-menu', inject: ['slots'], apply }
    return module.exports
  },
})
`
await writeFile(join(root, 'lib/client.js'), bundleClientTemplate('dsh-plugin-chat-menu'))
await writeFile(join(root, 'lib/client-registry.js'), bundleClientTemplate('dsh-external/dsh-plugin-chat-menu'))

// 4) Dynamic client: closure symbols (React / host are environment vars in
//    the dynamic evaluator) + host.call transport.
const dynClient = `// generated by scripts/build.mjs — single source: src/core/menu-core.ts
${coreText}
const list = (sessionId, path, filter) => host.call('fsmenu/list', { sessionId, path, filter })
const apply = CHATMENU_CORE.buildApply({ React, list })
return { name: 'dsh-plugin-chat-menu', apply }
`
await writeFile(join(root, 'dynamic/client.js'), dynClient)

console.log('built lib/index.js, lib/client.js, lib/client-registry.js, dynamic/host.js, dynamic/client.js')
